<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class RecursosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('recursos')->delete();
        $recursos=[
            
            [
                'recurso'=>'cotizaciones.index?aprobacion=0',
                'etiqueta'=>'APROB. VENTAS',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones.firmada',
                'etiqueta'=>'FIRMADAS',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones.index?aprobacion=3',
                'etiqueta'=>'APROB. SERVICIO',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones.index?aprobacion=2',
                'etiqueta'=>'APROB. CRED. Y COBR.',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones.index?aprobacion=1',
                'etiqueta'=>'APROB. MKT.',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones.index',
                'etiqueta'=>'VER MIS COTIZACIONES',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones.destroy',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones.update',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones.store',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones.create',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones.edit',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones_digitales.store',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones_digitales.index',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'2'
            ],
            //recursos
            [
                'recurso'=>'recursos.create',
                'observacion'=>'',
                'etiqueta'=>'CREAR',
                'id_menu'=>'2'
            ],
            [
                'recurso'=>'recursos.delete',
                'observacion'=>'',
                'etiqueta'=>'',
                'id_menu'=>'2'
            ],
            [
                'recurso'=>'recursos.index',
                'etiqueta'=>'VER',
                'observacion'=>'',
                'id_menu'=>'2'
            ],
            [
                'recurso'=>'recursos.index?vi=0',
                'etiqueta'=>'RESTAURAR',
                'observacion'=>'',
                'id_menu'=>'2'
            ],
            [
                'recurso'=>'recursos.store',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'2'
            ],
            [
                'recurso'=>'recursos.edit',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'2'
            ],
            [
                'recurso'=>'recursos.destroy',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'2'
            ],
            [
                'recurso'=>'recursos.update',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'2'
            ],
                        [
                'recurso'=>'cotizacionPaqueteInsumo.index',
                'etiqueta'=>'VER TODO',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizacionPaqueteInsumo.index?vista=0',
                'etiqueta'=>'RESTAURAR',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            //Marcas_proveedores
            [
                'recurso'=>'marcas_proveedores.create',
                'etiqueta'=>'CREAR',
                'observacion'=>'',
                'id_menu'=>'3'
            ],
            [
                'recurso'=>'marcas_proveedores.edit',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'3'
            ],
            [
                'recurso'=>'marcas_proveedores.update',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'3'
            ],
            [
                'recurso'=>'marcas_proveedores.store',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'3'
            ],
            [
                'recurso'=>'marcas_proveedores.destroy',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'3'
            ],
            [
                'recurso'=>'marcas_proveedores.index?vi=0',
                'etiqueta'=>'RESTAURAR',
                'observacion'=>'',
                'id_menu'=>'3'
            ],
            [
                'recurso'=>'marcas_proveedores.index',
                'etiqueta'=>'VER',
                'observacion'=>'',
                'id_menu'=>'3'
            ],
            
            //USERS
            [
                'recurso'=>'users.index',
                'etiqueta'=>'VER',
                'observacion'=>'',
                'id_menu'=>'6'
            ],
            [
                'recurso'=>'users.show',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'6'
            ],
            [
                'recurso'=>'users.store',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'6'
            ],
            [
                'recurso'=>'users.index?vista=0',
                'etiqueta'=>'RESTAURAR',
                'observacion'=>'',
                'id_menu'=>'6'
            ],
            [
                'recurso'=>'users.create',
                'etiqueta'=>'CREAR',
                'observacion'=>'',
                'id_menu'=>'6'
            ],
            [
                'recurso'=>'users.edit',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'6'
            ],
            [
                'recurso'=>'users.destroy',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'6'
            ],
            //INSUMOS
            [
                'recurso'=>'insumos.index',
                'etiqueta'=>'VER',
                'observacion'=>'',
                'id_menu'=>'7'
            ],
            [
                'recurso'=>'insumos.index?vi=0',
                'etiqueta'=>'RESTAURAR',
                'observacion'=>'',
                'id_menu'=>'7'
            ],
            [
                'recurso'=>'insumos.create',
                'etiqueta'=>'CREAR',
                'observacion'=>'',
                'id_menu'=>'7'
            ],
            [
                'recurso'=>'insumos.edit',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'7'
            ],
            [
                'recurso'=>'insumos.store',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'7'
            ],
            [
                'recurso'=>'insumos.update',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'7'
            ],
            [
                'recurso'=>'insumos.show',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'7'
            ],
            [
                'recurso'=>'insumo.destroy',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'7'
            ],
            [
                'recurso'=>'insumos-opcionales.index',
                'etiqueta'=>'RELACIONAR INSUMOS',
                'observacion'=>'',
                'id_menu'=>'7'
            ],
            [
                'recurso'=>'insumos-opcionales.store',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'7'
            ],
            //PAQUETES
            [
                'recurso'=>'paquetes.index',
                'etiqueta'=>'VER',
                'observacion'=>'',
                'id_menu'=>'8'
            ],
            [
                'recurso'=>'paquetes.index?vista=0',
                'etiqueta'=>'RESTAURAR',
                'observacion'=>'',
                'id_menu'=>'8'
            ],
            [
                'recurso'=>'paquetes.create',
                'etiqueta'=>'CREAR',
                'observacion'=>'',
                'id_menu'=>'8'
            ],
            [
                'recurso'=>'paquetes.edit',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'8'
            ],
            [
                'recurso'=>'paquetes.destroy',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'8'
            ],
            [
                'recurso'=>'paquetes.update',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'8'
            ],
            [
                'recurso'=>'paquetes.store',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'8'
            ],
            [
                'recurso'=>'paquetes.show',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'8'
            ],
            //catalogos calculo
            [
                'recurso'=>'catalogos_calculo.index',
                'etiqueta'=>'VER',
                'observacion'=>'',
                'id_menu'=>'10'
            ],
            [
                'recurso'=>'catalogos_calculo.index?vi=0',
                'etiqueta'=>'RESTAURAR',
                'observacion'=>'',
                'id_menu'=>'10'
            ],
            [
                'recurso'=>'catalogos_calculo.create',
                'etiqueta'=>'CREAR',
                'observacion'=>'',
                'id_menu'=>'10'
            ],
            [
                'recurso'=>'catalogos_calculo.edit',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'10'
            ],
            [
                'recurso'=>'catalogos_calculo.destroy',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'10'
            ],
            [
                'recurso'=>'catalogos_calculo.update',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'10'
            ],
            [
                'recurso'=>'catalogos_calculo.store',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'10'
            ],
            //contratos_compra venta
            [
                'recurso'=>'contratos_compra_venta.index',
                'etiqueta'=>'VER',
                'observacion'=>'',
                'id_menu'=>'11'
            ],
            [
                'recurso'=>'contratos_compra_venta.index?vi=0',
                'etiqueta'=>'RESTAURAR',
                'observacion'=>'',
                'id_menu'=>'11'
            ],
            [
                'recurso'=>'contratos_compra_venta.create',
                'etiqueta'=>'CREAR',
                'observacion'=>'',
                'id_menu'=>'11'
            ],
            [
                'recurso'=>'contratos_compra_venta.edit',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'11'
            ],
            [
                'recurso'=>'contratos_compra_venta.destroy',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'11'
            ],
            //PERMISOS
            [
                'recurso'=>'permisos.create',
                'etiqueta'=>'CREAR',
                'observacion'=>'',
                'id_menu'=>'1'
            ],
            //PRECALCULO
            [
                'recurso'=>'precalculos.create',
                'etiqueta'=>'CREAR',
                'observacion'=>'',
                'id_menu'=>'9'
            ],
            [
                'recurso'=>'precalculos.index',
                'etiqueta'=>'VER',
                'observacion'=>'',
                'id_menu'=>'9'
            ],
            [
                'recurso'=>'precalculos.index?vi=0',
                'etiqueta'=>'RESTAURAR',
                'observacion'=>'',
                'id_menu'=>'9'
            ],
            [
                'recurso'=>'precalculos.store',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'9'
            ],
            [
                'recurso'=>'precalculos.update',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'9'
            ],
            [
                'recurso'=>'precalculos.destroy',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'9'
            ],
            [
                'recurso'=>'precalculos.edit',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'9'
            ],
            //PAGARE
            [
                'recurso'=>'cotizaciones_digitales.edit',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            [
                'recurso'=>'cotizaciones_digitales.create',
                'etiqueta'=>'',
                'observacion'=>'',
                'id_menu'=>'4'
            ],
            //compras
            [
                'recurso'=>'compras.create',
                'etiqueta'=>'CREAR',
                'id_menu'=>'13',
                'observacion'=>'',
            ],
            [
                'recurso'=>'compras.restaurar',
                'etiqueta'=>'RESTAURAR',
                'id_menu'=>'13',
                'observacion'=>'',
            ],
            [
                'recurso'=>'compras.show',
                'etiqueta'=>'',
                'id_menu'=>'13',
                'observacion'=>'',
            ],
            [
                'recurso'=>'compras.destroy',
                'etiqueta'=>'',
                'id_menu'=>'13',
                'observacion'=>'',
            ],
            [
                'recurso'=>'compras.estatus',
                'etiqueta'=>'',
                'id_menu'=>'13',
                'observacion'=>'',
            ],
            [
                'recurso'=>'compras.edit',
                'etiqueta'=>'',
                'id_menu'=>'13',
                'observacion'=>'',
            ],
            [
                'recurso'=>'compras.update',
                'etiqueta'=>'',
                'id_menu'=>'13',
                'observacion'=>'',
            ],
            [
                'recurso'=>'compras.index',
                'etiqueta'=>'VER',
                'id_menu'=>'13',
                'observacion'=>'',
            ],
            [
                'recurso'=>'compras.store',
                'etiqueta'=>'',
                'id_menu'=>'13',
                'observacion'=>'',
            ],
            //CONDICIONES PAGOS
            [
                'recurso'=>'condiciones_pagos.destroy',
                'etiqueta'=>'',
                'id_menu'=>'14',
                'observacion'=>'',
            ],
            [
                'recurso'=>'condiciones_pagos.update',
                'etiqueta'=>'',
                'id_menu'=>'14',
                'observacion'=>'',
            ],
            [
                'recurso'=>'condiciones_pagos.edit',
                'etiqueta'=>'',
                'id_menu'=>'14',
                'observacion'=>'',
            ],
            [
                'recurso'=>'condiciones_pagos.show',
                'etiqueta'=>'',
                'id_menu'=>'14',
                'observacion'=>'',
            ],
            [
                'recurso'=>'condiciones_pagos.store',
                'etiqueta'=>'',
                'id_menu'=>'14',
                'observacion'=>'',
            ],
            [
                'recurso'=>'condiciones_pagos.index',
                'etiqueta'=>'VER',
                'id_menu'=>'14',
                'observacion'=>'',
            ],
            [
                'recurso'=>'condiciones_pagos.create',
                'etiqueta'=>'CREAR',
                'id_menu'=>'14',
                'observacion'=>'',
            ],
            [
                'recurso'=>'condiciones_pagos.restuarar',
                'etiqueta'=>'RESTAURAR',
                'id_menu'=>'14',
                'observacion'=>'',
            ],
            //AGENTES ADUANALES
            [
                'recurso'=>'agentes_aduanales.restuarar',
                'etiqueta'=>'RESTAURAR',
                'id_menu'=>'15',
                'observacion'=>'',
            ],
            [
                'recurso'=>'agentes_aduanales.update',
                'etiqueta'=>'',
                'id_menu'=>'15',
                'observacion'=>'',
            ],
            [
                'recurso'=>'agentes_aduanales.edit',
                'etiqueta'=>'',
                'id_menu'=>'15',
                'observacion'=>'',
            ],
            [
                'recurso'=>'agentes_aduanales.show',
                'etiqueta'=>'',
                'id_menu'=>'15',
                'observacion'=>'',
            ],
            [
                'recurso'=>'agentes_aduanales.store',
                'etiqueta'=>'',
                'id_menu'=>'15',
                'observacion'=>'',
            ],
            [
                'recurso'=>'agentes_aduanales.index',
                'etiqueta'=>'VER',
                'id_menu'=>'15',
                'observacion'=>'',
            ],
            [
                'recurso'=>'agentes_aduanales.create',
                'etiqueta'=>'CREAR',
                'id_menu'=>'15',
                'observacion'=>'',
            ]
        ];
//        $fin =4;
//        for ($i=0;$i<=$fin;$i++)
//        {
            \DB::table('recursos')->insert($recursos);   
//        }
    }
}
