<?php
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Precalculo extends Model
    {
                    //
                use SoftDeletes;              //  protected $dateFormat = 'd-m-Y';
                protected $dates = ['deleted_at'];
                    protected $table='precalculos';
    protected $fillable=[                //'id',
        'id_catalogo',
        'id_cotizaciones_paquetes_insumos',
        'fecha_catalogo',
        'moneda',
        'fecha_tipo_cambio',
        'tipo_cambio',
        'precio_dolares',
        'descuento',
        'precio_dolares_descuento',
        'impuesto_importacion',/**/
        'porcentaje_impuesto_importacion',
        'agente_aduanal',
        'h_agente_aduanal',
        'flete',
        'porcentaje_flete',
        'costo_instalacion',
        'porcentaje_costo_instalacion',
        'preparacion_sitio',
        'porcentaje_preparacion_sitio',
        'modelo_insumos',/**/
        'precio_compra_insumos',
        'porcentaje_insumos',
        'subtotal_1',
        'porcentaje_subtotal_1',
        'margen_bruto',
        'porcentaje_margen_bruto',
        'total_costo_instalacion_garantia',
        'porcentaje_garantia',
        'reserva_refaccion',
        'porcentaje_reserva_refaccion',/**/
        'garantia_adicional',
        'porcentaje_garantia_adicional',
        'patrocinio_congreso_publicacion',
        'porcentaje_patrocinio_congreso_publicacion',
        'cargo_bancario',
        'porcentaje_cargo_bancario',
        'subtotal_2',
        'porcentaje_subtotal_2',
        'financiera',
        'porcentaje_financiera',/**/
        'distribuidor',
        'porcentaje_distribuidor',
        'otros',
        'porcentaje_otros',
        'subtotal_3',
        'porcentaje_subtotal_3',
        'capacitacion',
        'porcentaje_capacitacion',
        'comision',
        'porcentaje_comision',/**/
        'margen_negocio',
        'porcentaje_margen_negocio',
        'precio_venta',
        'observaciones',
        'numero_proyecto',
        'venta_total_t_i',
        'valor_venta_e_i',/**/
        'valor_venta_servicio_e_p',
        'valor_venta_servicio_e_i',
        'valor_venta_servicio_s_p',/**/
        'valor_venta_servicio_s_i',/**/
        'valor_venta_servicio_t_p',
        'valor_venta_servicio_t_i',
        'costo_venta_producto_e_p',
        'costo_venta_producto_e_i',
        'costo_venta_producto_s_p',
        'costo_venta_producto_s_i',
        'costo_venta_producto_t_p',
        'costo_venta_producto_t_i',
        'costo_venta_terceros_e_p',
        'costo_venta_terceros_e_i',
        'costo_venta_terceros_s_p',
        'costo_venta_terceros_s_i',
        'costo_venta_terceros_t_p',
        'costo_venta_terceros_t_i',/**/
        'remplazo_parte_servicio_e_p',
        'remplazo_parte_servicio_e_i',
        'remplazo_parte_servicio_s_p',
        'remplazo_parte_servicio_s_i',
        'remplazo_parte_servicio_t_p',
        'remplazo_parte_servicio_t_i',
        'costo_material_e_p',
        'costo_material_e_i',
        'costo_material_s_p',
        'costo_material_s_i',
        'costo_material_t_p',
        'costo_material_t_i',
        'preparacion_sitio_e_p',
        'preparacion_sitio_e_i',
        'preparacion_sitio_s_p',/**/
        'preparacion_sitio_s_i',
        'preparacion_sitio_t_p',
        'preparacion_sitio_t_i',
        'preparacion_sitio_agente_e_p',
        'preparacion_sitio_agente_e_i',
        'preparacion_sitio_agente_s_p',
        'preparacion_sitio_agente_s_i',
        'preparacion_sitio_agente_t_p',
        'preparacion_sitio_agente_t_i',
        'preparacion_sitio_tercero_e_p',
        'preparacion_sitio_tercero_e_i',
        'preparacion_sitio_tercero_s_p',
        'preparacion_sitio_tercero_s_i',
        'preparacion_sitio_tercero_t_p',
        'preparacion_sitio_tercero_t_i',/**/
        'costo_instalacion_e_p',
        'costo_instalacion_e_i',
        'costo_instalacion_s_p',
        'costo_instalacion_s_i',
        'costo_instalacion_t_p',
        'costo_instalacion_t_i',
        'costo_instalacion_agente_e_p',
        'costo_instalacion_agente_e_i',
        'costo_instalacion_agente_s_p',
        'costo_instalacion_agente_s_i',
        'costo_instalacion_agente_t_p',
        'costo_instalacion_agente_t_i',
        'costo_instalacion_terceros_e_p',
        'costo_instalacion_terceros_e_i',
        'costo_instalacion_terceros_s_p',
        'costo_instalacion_terceros_s_i',
        'costo_instalacion_terceros_t_p',
        'costo_instalacion_terceros_t_i',/**/
        'mano_obra_subcontr_interna_e_p',
        'mano_obra_subcontr_interna_e_i',
        'mano_obra_subcontr_interna_s_p',
        'mano_obra_subcontr_interna_s_i',
        'mano_obra_subcontr_interna_t_p',
        'mano_obra_subcontr_interna_t_i',
        'mano_obra_subcontr_terceros_e_p',
        'mano_obra_subcontr_terceros_e_i',
        'mano_obra_subcontr_terceros_s_p',
        'mano_obra_subcontr_terceros_s_i',
        'mano_obra_subcontr_terceros_t_p',
        'mano_obra_subcontr_terceros_t_i',
        'capacitacion_cliente_e_p',
        'capacitacion_cliente_e_i',
        'capacitacion_cliente_s_p',
        'capacitacion_cliente_s_i',
        'capacitacion_cliente_t_p',
        'capacitacion_cliente_t_i',/**/
        'costo_venta_e_p',
        'costo_venta_e_i',
        'costo_venta_s_p',
        'costo_venta_s_i',
        'costo_venta_t_p',
        'costo_venta_t_i',
        'margen_bruto_e_p',
        'margen_bruto_e_i',
        'margen_bruto_s_p',
        'margen_bruto_s_i',
        'margen_bruto_t_p',
        'margen_bruto_t_i',
        'garantia_parte_e_p',
        'garantia_parte_e_i',
        'garantia_parte_s_p',
        'garantia_parte_s_i',
        'garantia_parte_t_p',
        'garantia_parte_t_i',/**/
        'garantia_mano_obra_e_p',
        'garantia_mano_obra_e_i',
        'garantia_mano_obra_s_p',
        'garantia_mano_obra_s_i',
        'garantia_mano_obra_t_p',
        'garantia_mano_obra_t_i',
        'comision_pagar_tercero_e_p',
        'comision_pagar_tercero_e_i',
        'comision_pagar_tercero_s_p',
        'comision_pagar_tercero_s_i',
        'comision_pagar_tercero_t_p',
        'comision_pagar_tercero_t_i',
        'comision_agente_venta_e_p',
        'comision_agente_venta_e_i',
        'comision_agente_venta_s_p',
        'comision_agente_venta_s_i',
        'comision_agente_venta_t_p',
        'comision_agente_venta_t_i',/**/
        'servicio_externo_e_p',
        'servicio_externo_e_i',
        'servicio_externo_s_p',
        'servicio_externo_s_i',
        'servicio_externo_t_p',
        'servicio_externo_t_i',
        'capacitacion_personal_e_p',
        'capacitacion_personal_e_i',
        'capacitacion_personal_s_p',
        'capacitacion_personal_s_i',
        'capacitacion_personal_t_p',
        'capacitacion_personal_t_i',
        'publicidad_patrocinio_congreso_e_p',
        'publicidad_patrocinio_congreso_e_i',
        'publicidad_patrocinio_congreso_s_p',
        'publicidad_patrocinio_congreso_s_i',
        'publicidad_patrocinio_congreso_t_p',
        'publicidad_patrocinio_congreso_t_i',/**/
        'cargo_bancario_e_p',
        'cargo_bancario_e_i',
        'cargo_bancario_s_p',
        'cargo_bancario_s_i',
        'cargo_bancario_t_p',
        'cargo_bancario_t_i',
        'costo_financiero_e_p',
        'costo_financiero_e_i',
        'costo_financiero_s_p',
        'costo_financiero_s_i',
        'costo_financiero_t_p',
        'costo_financiero_t_i',
        'gasto_viaje_cliente_e_p',
        'gasto_viaje_cliente_e_i',
        'gasto_viaje_cliente_s_p',
        'gasto_viaje_cliente_s_i',
        'gasto_viaje_cliente_t_p',
        'gasto_viaje_cliente_t_i',
        'gasto_viaje_personal_smh_e_p',
        'gasto_viaje_personal_smh_e_i',
        'gasto_viaje_personal_smh_s_p',
        'gasto_viaje_personal_smh_s_i',
        'gasto_viaje_personal_smh_t_p',
        'gasto_viaje_personal_smh_t_i',
        'impuesto_aduanal_e_p',
        'impuesto_aduanal_e_i',
        'impuesto_aduanal_s_p',
        'impuesto_aduanal_s_i',
        'impuesto_aduanal_t_p',
        'impuesto_aduanal_t_i',
        'flete_e_p',
        'flete_e_i',
        'flete_s_p',
        'flete_s_i',
        'flete_t_p',
        'flete_t_i',
        'seguro_e_p',
        'seguro_e_i',
        'seguro_s_p',
        'seguro_s_i',
        'seguro_t_p',
        'seguro_t_i',
        'costo_proyecto_e_p',
        'costo_proyecto_e_i',
        'costo_proyecto_s_p',
        'costo_proyecto_s_i',
        'costo_proyecto_t_p',
        'costo_proyecto_t_i',
        'gasto_venta_dedicado_e_p',
        'gasto_venta_dedicado_e_i',
        'gasto_venta_dedicado_s_p',
        'gasto_venta_dedicado_s_i',
        'gasto_venta_dedicado_t_p',
        'gasto_venta_dedicado_t_i'
	];
   public function scopeId($query,$id)
    {
        if(trim($id)!="")
        {
            $arr=explode("*", $id);
            if(count($arr)>=2)
            {
                $id=  str_replace("*", "%", $id);
                $query->where('id','like',$id);
            }  else 
            {
                $query->where('id',$id);
            }
        }
    }	
    public function scopeIdCotizacionesPaquetesInsumos($query,$id_cotizaciones_paquetes_insumos)
    {
        if(trim($id_cotizaciones_paquetes_insumos)!="")
        {
            $arr=explode("*", $id_cotizaciones_paquetes_insumos);
            if(count($arr)>=2)
            {
                $id_cotizaciones_paquetes_insumos=  str_replace("*", "%", $id_cotizaciones_paquetes_insumos);
                $query->where('id_cotizaciones_paquetes_insumos','like',$id_cotizaciones_paquetes_insumos);
            }  else 
            {
                $query->where('id_cotizaciones_paquetes_insumos',$id_cotizaciones_paquetes_insumos);
            }
        }
    }
    public function scopeNumeroProyecto($query,$numero_proyecto)
    {
        if(trim($numero_proyecto)!="")
        {
            $arr=explode("*", $numero_proyecto);
            if(count($arr)>=2)
            {
                $numero_proyecto=  str_replace("*", "%", $numero_proyecto);
                $query->where('numero_proyecto','like',$numero_proyecto);
            }  else 
            {
                $query->where('numero_proyecto',$numero_proyecto);
            }
        }
    } public function scopeFechaCreacion($query,$fecha_creacion)
    {
        if(trim($fecha_creacion)!="")
        {
            $arr=explode("*", $fecha_creacion);
            if(count($arr)>=2)
            {
                $numero_proyecto=  str_replace("*", "%", $fecha_creacion);
                $query->where('created_at','like',$fecha_creacion);
            }  else 
            {
                $query->where('created_at',$fecha_creacion);
            }
        }
    }	  
}
